export const FORM_CHANGE="FORM_CHANGE";
export const CHANGE_NEWADVISERFORM="CHANGE_NEWADVISERFORM";
export const CHANGE_NEWORDERFORM="CHANGE_NEWORDERFORM";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CHANGE_TESTFORM="CHANGE_TESTFORM"
export const SET_FORM1RESPONSE="SET_FORM1RESPONSE"